# Generated by Django 4.0.5 on 2022-07-20 09:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Food category', max_length=255, verbose_name='Food category')),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Food name', max_length=50, verbose_name='Name')),
                ('description', models.CharField(help_text='Food name', max_length=255, verbose_name='Name')),
                ('price', models.FloatField(default=0, help_text='Price of food item')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Restaurant name', max_length=255, verbose_name='Name')),
                ('address', models.CharField(help_text='Restaurant address', max_length=255, verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Review description', max_length=255, verbose_name='description')),
                ('rating', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('restaurant', models.OneToOneField(help_text='Restaurant review', on_delete=django.db.models.deletion.CASCADE, to='api.restaurant', verbose_name='Restaurant review')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_items', models.ManyToManyField(to='api.fooditem')),
                ('restaurant', models.OneToOneField(help_text='Restaurant menu', on_delete=django.db.models.deletion.CASCADE, to='api.restaurant', verbose_name='Restaurant menu')),
            ],
        ),
    ]
