# Generated by Django 4.0.5 on 2022-08-16 04:58

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
                ('name', models.CharField(help_text='Food category', max_length=255, verbose_name='Food category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
                ('name', models.CharField(help_text='Food name', max_length=50, verbose_name='Name')),
                ('description', models.CharField(help_text='Food Description', max_length=255, verbose_name='Description')),
                ('price', models.PositiveIntegerField(default=0, help_text='Price of food item')),
                ('is_active', models.BooleanField(default=True, help_text='Is active?', verbose_name='Is active?')),
                ('category', models.ForeignKey(help_text='Food category', on_delete=django.db.models.deletion.DO_NOTHING, related_name='food_items', to='api.category', verbose_name='Food category')),
            ],
            options={
                'verbose_name': 'Food item',
                'verbose_name_plural': 'Food items',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
                ('name', models.CharField(help_text='Restaurant name', max_length=255, verbose_name='Name')),
                ('address', models.CharField(help_text='Restaurant address', max_length=255, verbose_name='Address')),
                ('latitude', models.FloatField(help_text='Restaurant latitude', verbose_name='Latitude')),
                ('longitude', models.FloatField(help_text='Restaurant longitude', verbose_name='Longitude')),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('is_staff', models.BooleanField(default=False, help_text='Is Staff', verbose_name='Is Staff')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
                ('description', models.CharField(help_text='Review description', max_length=255, verbose_name='Description')),
                ('rating', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('restaurant', models.OneToOneField(help_text='Restaurant review', on_delete=django.db.models.deletion.DO_NOTHING, to='api.restaurant', verbose_name='Restaurant review')),
                ('user', models.ForeignKey(help_text='User', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
                ('quantity', models.PositiveSmallIntegerField(default=1, help_text='Quantity', verbose_name='Quantity')),
                ('food_item', models.ForeignKey(help_text='Food item', on_delete=django.db.models.deletion.DO_NOTHING, to='api.fooditem', verbose_name='Food item')),
            ],
            options={
                'verbose_name': 'Order item',
                'verbose_name_plural': 'Order items',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
                ('complete', models.BooleanField(default=False, help_text='Is complete?', verbose_name='Is complete?')),
                ('transaction_id', models.CharField(help_text='Transaction ID', max_length=255, verbose_name='Transaction ID')),
                ('is_paid', models.BooleanField(default=False, help_text='Is paid?', verbose_name='Is paid?')),
                ('received', models.BooleanField(default=False, help_text='Is received?', verbose_name='Is received?')),
                ('table_number', models.PositiveSmallIntegerField(help_text='Table number', verbose_name='Table number')),
                ('order_item', models.ManyToManyField(help_text='Order items', related_name='order_items', to='api.orderitem', verbose_name='Order items')),
                ('restaurant', models.ForeignKey(help_text='Restaurant', on_delete=django.db.models.deletion.DO_NOTHING, to='api.restaurant', verbose_name='Restaurant')),
                ('user', models.ForeignKey(help_text='User that ordered', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='User that ordered')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
                ('food_items', models.ManyToManyField(help_text='Food items', to='api.fooditem', verbose_name='Food items')),
                ('restaurant', models.OneToOneField(help_text='Restaurant menu', on_delete=django.db.models.deletion.DO_NOTHING, to='api.restaurant', verbose_name='Restaurant menu')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.restaurant')),
                ('user', models.OneToOneField(help_text='User manager', on_delete=django.db.models.deletion.CASCADE, to='api.user', verbose_name='User manager')),
            ],
            options={
                'verbose_name': 'Manager',
                'verbose_name_plural': 'Managers',
            },
        ),
    ]
